// SPDX-License-Identifier: CC0-1.0

//! Auto-generated bindings for Bitcoin Core `30`.
//!
//! Generated by `rust-btc-codegen`. **Do not edit any file in this module by hand.**
//! Re-run `just codegen` from the workspace root to regenerate.
//!
//! # Layout
//!
//! * [`types`]   — return types for every RPC (raw, version-specific shape).
//! * [`options`] — `*Options` structs for methods with optional positional arguments.
//! * [`methods`] — `impl Raw<'_>` blocks calling `Client::call_raw`.
//!
//! Hand-written `into_model()`-style wrappers live in `client_async::model::v30`,
//! which is *not* part of this module.

// Doc comments below are copied verbatim from Bitcoin Core's RPC help. They contain bare
// URLs and bracketed parameter references (e.g. `[minconf]`) that rustdoc cannot resolve
// as Rust intra-doc links. Silencing locally is preferable to mangling the upstream prose.
#![allow(rustdoc::bare_urls, rustdoc::broken_intra_doc_links)]

pub mod methods;
pub mod options;
pub mod types;

pub use options::*;
pub use types::*;
